### ISSUE TITLE
Can't find native library in Linux

### ISSUE THREAD

**Issue by zerofancy** [webview/webview_java#27]
OS: Debian GNU/Linux 12 (bookworm) x86_64
Kernel: 6.1.0-18-amd64
DE: Plasma 5.27.5

I cloned the project and run example project, and got an error:

```
Exception in thread "main" java.lang.UnsatisfiedLinkError: Unable to load library 'webview':
libwebview.so: 无法打开共享对象文件: 没有那个文件或目录
libwebview.so: 无法打开共享对象文件: 没有那个文件或目录
Native library (linux-x86-64/libwebview.so) not found in resource path (/home/zero/IdeaProjects/webview_java/examples/target/classes:/home/zero/IdeaProjects/webview_java/bridge/target/classes:/home/zero/.m2/repository/co/casterlabs/commons/async/1.7.0/async-1.7.0.jar:/home/zero/.m2/repository/co/casterlabs/rson/1.17.9/rson-1.17.9.jar:/home/zero/IdeaProjects/webview_java/core/target/classes:/home/zero/.m2/repository/co/casterlabs/commons/platform/1.7.0/platform-1.7.0.jar:/home/zero/.m2/repository/co/casterlabs/commons/io/1.7.0/io-1.7.0.jar:/home/zero/.m2/repository/net/java/dev/jna/jna/5.14.0/jna-5.14.0.jar:/home/zero/.m2/repository/net/java/dev/jna/jna-platform/5.14.0/jna-platform-5.14.0.jar:/home/zero/.m2/repository/org/openjfx/javafx-base/19.0.2.1/javafx-base-19.0.2.1.jar:/home/zero/.m2/repository/org/openjfx/javafx-base/19.0.2.1/javafx-base-19.0.2.1-linux.jar:/home/zero/.m2/repository/org/openjfx/javafx-graphics/19.0.2.1/javafx-graphics-19.0.2.1.jar:/home/zero/.m2/repository/org/openjfx/javafx-graphics/19.0.2.1/javafx-graphics-19.0.2.1-linux.jar)
	at com.sun.jna.NativeLibrary.loadLibrary(NativeLibrary.java:325)
	at com.sun.jna.NativeLibrary.getInstance(NativeLibrary.java:481)
	at com.sun.jna.Library$Handler.<init>(Library.java:197)
	at com.sun.jna.Native.load(Native.java:618)
	at dev.webview.webview_java.WebviewNative.runSetup(WebviewNative.java:108)
	at dev.webview.webview_java.WebviewNative.<clinit>(WebviewNative.java:46)
	at dev.webview.webview_java.Webview.<init>(Webview.java:140)
	at dev.webview.webview_java.Webview.<init>(Webview.java:132)
	at dev.webview.webview_java.Webview.<init>(Webview.java:79)
	at dev.webview.webview_java.example.direct.Example.main(Example.java:8)
	Suppressed: java.lang.UnsatisfiedLinkError: libwebview.so: 无法打开共享对象文件: 没有那个文件或目录
		at com.sun.jna.Native.open(Native Method)
		at com.sun.jna.NativeLibrary.loadLibrary(NativeLibrary.java:213)
		... 9 more
	Suppressed: java.lang.UnsatisfiedLinkError: libwebview.so: 无法打开共享对象文件: 没有那个文件或目录
		at com.sun.jna.Native.open(Native Method)
		at com.sun.jna.NativeLibrary.loadLibrary(NativeLibrary.java:226)
		... 9 more
	Suppressed: java.io.IOException: Native library (linux-x86-64/libwebview.so) not found in resource path (/home/zero/IdeaProjects/webview_java/examples/target/classes:/home/zero/IdeaProjects/webview_java/bridge/target/classes:/home/zero/.m2/repository/co/casterlabs/commons/async/1.7.0/async-1.7.0.jar:/home/zero/.m2/repository/co/casterlabs/rson/1.17.9/rson-1.17.9.jar:/home/zero/IdeaProjects/webview_java/core/target/classes:/home/zero/.m2/repository/co/casterlabs/commons/platform/1.7.0/platform-1.7.0.jar:/home/zero/.m2/repository/co/casterlabs/commons/io/1.7.0/io-1.7.0.jar:/home/zero/.m2/repository/net/java/dev/jna/jna/5.14.0/jna-5.14.0.jar:/home/zero/.m2/repository/net/java/dev/jna/jna-platform/5.14.0/jna-platform-5.14.0.jar:/home/zero/.m2/repository/org/openjfx/javafx-base/19.0.2.1/javafx-base-19.0.2.1.jar:/home/zero/.m2/repository/org/openjfx/javafx-base/19.0.2.1/javafx-base-19.0.2.1-linux.jar:/home/zero/.m2/repository/org/openjfx/javafx-graphics/19.0.2.1/javafx-graphics-19.0.2.1.jar:/home/zero/.m2/repository/org/openjfx/javafx-graphics/19.0.2.1/javafx-graphics-19.0.2.1-linux.jar)
		at com.sun.jna.Native.extractFromResourcePath(Native.java:1141)
		at com.sun.jna.NativeLibrary.loadLibrary(NativeLibrary.java:297)
		... 9 more

Process finished with exit code 1
```

It seems that the native library is placed to a wrong path, so I tried to make a copy of it, which works very well.

![image](https://github.com/webview/webview_java/assets/40628516/19faff9b-1d58-4d94-a05b-5b24d6344a14)

**Comment by e3ndr** [comment]
Alright I've pushed out a hopeful fix. Let me know how it goes.

**Comment by zerofancy** [comment]
> Alright I've pushed out a hopeful fix. Let me know how it goes.

It works now.
